// src/app/components/resultado-perfil/resultado-perfil.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { GithubUser } from '../shared/models/github-user.model';

@Component({
  selector: 'app-resultado-perfil',
  templateUrl: './resultado-perfil.component.html',
  styleUrls: ['./resultado-perfil.component.scss']
})
export class ResultadoPerfilComponent implements OnInit {

  @Input()
  dadosPerfil: GithubUser

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container">
  <img
    [src]="dadosPerfil.avatar_url"
    alt="Avatar do perfil no GitHub"
  >

  <h2> {{ dadosPerfil.name }}</h2>

  <strong><p> {{dadosPerfil.location}} </p></strong>
</div>

// src/app/components/react/resultado-perfil/resultado-perfil.tsx

import * as React from 'react';

export default function ResultadoPerfil(props) {

  const styling = {
    container: {
      display: 'flex',
      flexDirection: 'column' as 'column',
      alignItems: 'center',
      color: '#ffffff',
      marginTop: '20px',
    },
    imagem: {
      maxWidth: '200px',
      margin: '0 auto',
    },
  }

    return (
        <>
          <div style={styling.container}>
            <img
              src={props.githubUser.avatar_url}
              alt="Avatar do perfil no GitHub"
              style={styling.imagem}
            />

            <h2> { props.githubUser.name }</h2>

            <strong><p> {props.githubUser.location} </p></strong>
          </div>
        </>
    )

}
