// src/app/components/react/busca-github/busca-github.tsx

import * as React from 'react';
import { useState } from 'react';
import ResultadoPerfil from '../resultado-perfil/resultado-perfil';
import ResultadoRepos from '../resultado-repos/resultado.repos';
import { GithubUser } from "../../../shared/models/github-user.model";
import { api } from "../../../shared/services/github.service.react";
import { GithubRepo } from 'src/app/shared/models/github-repo.model';

export default function ComponenteReact() {

    const [user, setUser] = useState('');
    const [exibePerfil, setExibePerfil] = useState(false);
    const [exibeRepos, setExibeRepos] = useState(false);
    const [githubUser, setGithubUser] = useState<GithubUser>(new GithubUser());
    const [githubRepos, setGithubRepos] = useState<GithubRepo[]>([]);
    bla: Boolean;

    const styling = {
      cardBusca: {
        backgroundColor: '#3d8bfd',
        padding: '20px',
        marginBottom: '20px',
      },
      form: {
        display: 'flex',
        height: '20%',
        alignItems: 'center',
        justifyContent: 'space-between',
      },
      usuarioGithub: {
        flex: 1,
        height: '50px',
        borderRadius: '5px',
        borderStyle: 'hidden',
        outlineWidth: 0,
        marginRight: '20px',
        textAlign: 'center' as 'center',
        fontSize: 'large',
        paddingLeft: '20px',
      }
    }

    function handleRegister(event) {


      api.get(`${user}`)
      .then(response => {
        setGithubUser(response.data);
      })

      event.preventDefault();
      setExibePerfil(true);
      obterRepositorios();
    }

    function obterRepositorios() {
      api.get(`${user}/repos`)
      .then(response => {
        setGithubRepos(response.data);
        setExibeRepos(true);
      })
    }

    return (
        <>
          <div className="container-fluid">
            <div className="card" style={styling.cardBusca}>
              <form style={styling.form} onSubmit={handleRegister}>
                <input
                  type="text"
                  placeholder="Digite o usuário Github"
                  style={styling.usuarioGithub}
                  onChange={event => setUser(event.target.value)}
                  required
                />
                <button type="submit" className="btn btn-info"> Buscar</button>
              </form>
              {exibePerfil ? <ResultadoPerfil githubUser={githubUser}/> : null}
            </div>
            {exibeRepos ? <ResultadoRepos githubRepos={githubRepos}/> : null}
          </div>
        </>
    )

}

// src/app/components/busca-github/busca-github.component.ts
import { Component, OnInit } from '@angular/core';
import { GithubService } from '../../shared/services/github.service';
import { flatMap, take } from 'rxjs/operators';
import { GithubUser } from '../../shared/models/github-user.model';
import { FormControl, FormGroup } from '@angular/forms';
import { GithubRepo } from '../../shared/models/github-repo.model';

@Component({
  selector: 'app-busca-github',
  templateUrl: './busca-github.component.html',
  styleUrls: ['./busca-github.component.scss']
})
export class BuscaGithubComponent implements OnInit {

  exibePerfil = false;
  exibeRepos = false;
  dadosPerfil: GithubUser;
  dadosRepos: GithubRepo[];

  form = new FormGroup({
    githubUser: new FormControl('')
  });


  constructor(
    private githubService: GithubService
  ) { }

  ngOnInit(): void {
  }

  buscaGithubUser(): void {

    this.exibePerfil = false;
    this.exibeRepos = false;

    const user = this.form.controls['githubUser'].value;

    this.githubService.obterDadosUsuario(user)
      .pipe(
        take(1)
      )
      .subscribe( (usr: GithubUser) => {
        this.exibePerfil = true;
        this.dadosPerfil = usr;
        this.githubService.obterRepositoriosPublicos(user)
        .pipe(
          take(1)
        )
        .subscribe( (repos: GithubRepo[]) => {
          this.dadosRepos = repos;
          this.exibeRepos = true;
          console.log(repos);
        }

         )
      }

      )
  }

  buscaGithubRepos(): void {

    const user = this.form.controls['githubUser'].value;


    this.githubService.obterDadosUsuario(user)
      .pipe(
        take(1)
      )
      .subscribe( (usr: GithubUser) => {
        console.log(usr);
        this.githubService.obterRepositoriosPublicos(user)
        .pipe(
          take(1)
        )
        .subscribe( (repos: GithubRepo[]) => {
          console.log(repos);
        }

         )
      }

      )
  }

}

<div class="container">
  <div class="card">
    <form>
      <input
        type="text"
        placeholder="Digite o usuário Github"
        [formControl]="form.controls['githubUser']"
        class="usuario-github"
      >
      <button type="button" class="btn btn-info" (click)="buscaGithubUser()"> Buscar</button>
    </form>
    <app-resultado-perfil
      *ngIf="exibePerfil"
      [dadosPerfil]="dadosPerfil"
      class="resultado-perfil"
    >

    </app-resultado-perfil>
  </div>

  <app-resultado-repos
   *ngIf="exibeRepos"
   [dadosRepos]="dadosRepos"
  >

  </app-resultado-repos>
</div>
