// src/app/components/react/busca-github/busca-github.component.tsx

import * as React from 'react';
import { styling } from "./busca-github.styles";

export default function ComponenteReact() {


    return (
        <>
          <div className="container-fluid">
            <div className="card" style={styling.cardBusca}>
              <form style={styling.form}>
                <input
                  type="text"
                  placeholder="Digite o usuário Github"
                  style={styling.usuarioGithub}
                  required
                />
                <button type="submit" className="btn btn-info"> Buscar</button>
              </form>
            </div>
          </div>
        </>
    )

}

// src/app/components/busca-github/busca-github.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-busca-github',
  templateUrl: './busca-github.component.html',
  styleUrls: ['./busca-github.component.scss']
})
export class BuscaGithubComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<button
  (click)="ligaDesligaReact()"
  class="btn"
  [ngClass]="{
    'btn-success': habilitaReact,
    'btn-danger': !habilitaReact
  }"
>
  TOGGLE REACT - {{habilitaReact ? 'ON' : 'OFF'}}
</button>
<div class="container-fluid" *ngIf="!habilitaReact">
  <div
    class="card card-busca"
    [class.inicial]="!exibePerfil && !exibeRepos"
  >
    <form [formGroup]="form">
      <input
        type="text"
        placeholder="Digite o usuário Github"
        formControlName="githubUser"
        class="usuario-github"
        [class.invalido]="erroInput"
        required
      >
      <button type="submit" class="btn btn-info" (click)="buscaGithubUser()"> Buscar</button>
    </form>
    <app-resultado-perfil
      *ngIf="exibePerfil"
      [dadosPerfil]="dadosPerfil"
      class="resultado-perfil"
    >

    </app-resultado-perfil>
    <div
      class="spinner-border text-primary"
      role="status"
      *ngIf="carregandoPerfil"
    >
      <span class="visually-hidden">Obtendo Dados...</span>
    </div>
  </div>

  <app-resultado-repos
   *ngIf="exibeRepos"
   [dadosRepos]="dadosRepos"
  >

  </app-resultado-repos>
    <div
      class="spinner-border text-primary"
      role="status"
      *ngIf="carregandoPerfil"
    >
      <span class="visually-hidden">Obtendo Dados...</span>
    </div>
</div>
<app-react-wrapper *ngIf="habilitaReact"></app-react-wrapper>
