// src/app/components/react/resultado-repos/resultado.repos.tsx

import * as React from 'react';

export default function ResultadoRepos(props) {

    return (
        <>
          <div className="container">
            <h1> Lista de Repositórios Públicos</h1>

            {
              props.githubRepos.map((repo, index) => {
                return (
                  <div className="row">
                    <div className="col-12">
                      <div className="card">
                        <div className="card-body">
                          <h5 className="card-title"><a href={repo.html_url} className="card-link">{ repo.name }</a></h5>
                          <h6 className="card-subtitle mb-2 text-muted"> { repo.stargazers_count } Estrelas</h6>
                          <p className="card-text"> {repo.description} </p>
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })
            }
          </div>
        </>
    )

}

// src/app/components/resultado-repos/resultado-repos.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { GithubRepo } from '../../shared/models/github-repo.model';

@Component({
  selector: 'app-resultado-repos',
  templateUrl: './resultado-repos.component.html',
  styleUrls: ['./resultado-repos.component.scss']
})
export class ResultadoReposComponent implements OnInit {

  @Input()
  dadosRepos: GithubRepo[]

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container">
  <h1> Lista de Repositórios Públicos</h1>
  <div class="row">
    <div class="col-12" *ngFor="let repo of dadosRepos; let id = index">
      <div class="card" style="margin-bottom: 20px;">
        <div class="card-body">
          <h5 class="card-title"><a [href]="repo.html_url" class="card-link">{{ repo.name }}</a></h5>
          <h6 class="card-subtitle mb-2 text-muted"> {{ repo.stargazers_count }} Estrelas</h6>
          <p class="card-text"> {{repo.description}} </p>
        </div>
      </div>
    </div>
  </div>
</div>
